#!/bin/bash

if [ "$#" == 2 ]
then

    DAY=$(echo $1 | cut -c1-2)
    MONTH=$(echo $1 | cut -c4-5)
    YEAR=$(echo $1 | cut -c7-11)
    shift
    SEARCH_ARG=$(echo "$MONTH/$DAY/$YEAR")
    START_TIME=$(date -d "$SEARCH_ARG" +'%s')
    END_TIME=$(echo "$START_TIME + 24*60*60" | bc)

    URL='https://aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=csv&stationString='"$1"'&startTime='"$START_TIME"'&endTime='"$END_TIME"''

elif [ "$#" == 1 ]
then
    END=$(date +"%m/%d/%Y")
    END_TIME=$(date -d "$END" +'%s')
    
    START=$(date -d yesterday +"%m/%d/%Y")
    START_TIME=$(date -d "$START" +'%s')


    
    URL='https://aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=csv&stationString='"$1"'&startTime='"$START_TIME"'&endTime='"$END_TIME"''

else
    exit 1
fi
curl -s "$URL" |
    grep "$1"
